jwt:
  issuer: slothfkdla@gmail.com
  secret: oNlbC1SXEr6jig2XEvlZdhFULBbhukaY
logging:
  file:
    name: log/lotte.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: debug
    root: info
server:
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: a1s2d3F$
    url: jdbc:mysql://13.209.17.103:3306/LotteON
    username: lotte
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  jpa:
    database: mysql
    hibernate:
      #ddl-auto: update
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
    # prefix ??? ??? HTML ?? ? ?????? ???? ????
    prefix: classpath:/templates
  servlet:
    multipart:
      location: src/main/resources/static/file/
      max-file-size: 10MB